## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
df = application_df.drop(columns=['EIN', 'NAME'])

In [ ]:
# Determine the number of unique values in each column.
df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning# Assuming 'df' is your DataFrame
app_value_counts = df['APPLICATION_TYPE'].value_counts()

In [ ]:
app_value_counts.unique()

array([27037,  1542,  1216,  1173,  1065,   737,   725,   528,   156,
          66,    27,    16,     3,     2,     1])

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = app_value_counts[app_value_counts < 150].keys() #['T13', 'T12','T2','T25','T14','T29','T15','T17']

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
classification_counts = df['CLASSIFICATION'].value_counts()

In [ ]:
classification_counts.unique()

array([17326,  6074,  4837,  1918,  1883,   777,   287,   194,   116,
         114,   104,    95,    75,    58,    50,    36,    34,    32,
          30,    20,    18,    16,    15,    14,    11,    10,     9,
           7,     6,     5,     3,     2,     1])

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = classification_counts[classification_counts < 60].keys()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      499
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
training_df = pd.get_dummies(df)
training_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [ ]:
# Split our preprocessed data into our features and target arrays
y=training_df['IS_SUCCESSFUL']
X=training_df.drop(columns='IS_SUCCESSFUL')

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=50, activation="relu", input_dim=116))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=120, activation="relu"))
nn.add(tf.keras.layers.Dense(units=60, activation="relu"))
nn.add(tf.keras.layers.Dense(units=10, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_13"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_68 (Dense)            (None, 50)                5850

 dense_69 (Dense)            (None, 120)               6120

 dense_70 (Dense)            (None, 60)                7260

 dense_71 (Dense)            (None, 10)                610

 dense_72 (Dense)            (None, 1)                 11

=================================================================
Total params: 19851 (77.54 KB)
Trainable params: 19851 (77.54 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 4s 4ms/step - loss: 0.5741 - accuracy: 0.7198
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5521 - accuracy: 0.7292
Epoch 3/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5490 - accuracy: 0.7311
Epoch 4/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5465 - accuracy: 0.7323
Epoch 5/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5457 - accuracy: 0.7324
Epoch 6/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5447 - accuracy: 0.7350
Epoch 7/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5436 - accuracy: 0.7346
Epoch 8/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5423 - accuracy: 0.7355
Epoch 9/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5423 - accuracy: 0.7350
Epoch 10/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5411 - accuracy: 0.7361
Epoch 11/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5407 - accuracy: 0.7364
Epoch 12/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5395 - accuracy: 0.7383
Epoch 13/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5388 - accuracy: 0.7381
Epoch 14/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5393 - accuracy: 0.7375
Epoch 15/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5384 - accuracy: 0.7384
Epoch 16/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5379 - accuracy: 0.7381
Epoch 17/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5376 - accuracy: 0.7390
Epoch 18/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5369 - accuracy: 0.7395
Epoch 19/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5373 - accuracy: 0.7383
Epoch 20/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5363 - accuracy: 0.7391
Epoch 21/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5355 - accuracy: 0.7395
Epoch 22/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5354 - accuracy: 0.7393
Epoch 23/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5351 - accuracy: 0.7406
Epoch 24/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5348 - accuracy: 0.7399
Epoch 25/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5344 - accuracy: 0.7399
Epoch 26/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5342 - accuracy: 0.7394
Epoch 27/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5341 - accuracy: 0.7407
Epoch 28/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5341 - accuracy: 0.7406
Epoch 29/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5338 - accuracy: 0.7406
Epoch 30/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5329 - accuracy: 0.7393
Epoch 31/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5330 - accuracy: 0.7405
Epoch 32/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5330 - accuracy: 0.7406
Epoch 33/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5324 - accuracy: 0.7408
Epoch 34/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5319 - accuracy: 0.7406
Epoch 35/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5324 - accuracy: 0.7410
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5324 - accuracy: 0.7412
Epoch 37/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5319 - accuracy: 0.7407
Epoch 38/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5315 - accuracy: 0.7415
Epoch 39/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5309 - accuracy: 0.7414
Epoch 40/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5317 - accuracy: 0.7419
Epoch 41/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5308 - accuracy: 0.7416
Epoch 42/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5306 - accuracy: 0.7411
Epoch 43/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5305 - accuracy: 0.7413
Epoch 44/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5308 - accuracy: 0.7422
Epoch 45/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5307 - accuracy: 0.7411
Epoch 46/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5303 - accuracy: 0.7428
Epoch 47/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5303 - accuracy: 0.7416
Epoch 48/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5297 - accuracy: 0.7413
Epoch 49/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5293 - accuracy: 0.7422
Epoch 50/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5301 - accuracy: 0.7413

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5609 - accuracy: 0.7313 - 509ms/epoch - 2ms/step
Loss: 0.5609182119369507, Accuracy: 0.7313119769096375

In [ ]:
# Export our model to HDF5 file
nn.save('umn_data_nn_challenge.h5')